# Generated by Django 3.2.7 on 2022-05-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
